language: python
sudo: false

env:
  - LUA="lua=5.1"

before_install:
  - pip install hererocks
  - pip install codecov
  - hererocks here --$LUA -r latest
  - source here/bin/activate
  - luarocks install luacheck

script:
  - luacheck MYDev_Snaplines MYDev_UIEventID MYDev_UITexViewer MYDev_VarWatch 'MY_!Base' MY_BagEx MY_Cataclysm MY_Chat MY_ChatFilter MY_ChatLog MY_ChatMonitor MY_CombatText MY_Farbnamen MY_Focus MY_Font MY_FontResource MY_Force MY_GKP MY_LifeBar MY_Logoff MY_MiddleMapMark MY_Recount MY_Resource MY_RoleStatistics MY_RollMonitor MY_ScreenShot MY_TalkEx MY_Target MY_TargetMon MY_TeamMon MY_TeamTools MY_ThreatRank MY_Toolbox
